server {
    listen 80;
    server_name wd5.madeline.sh;

    location / {
        proxy_pass http://localhost:7141;
    }
}

server {
    listen 80;
    server_name wolfda.sh;

    location = / {
        return 301 /5;
    }

    location = /5 {
        return 301 /5/;
    }

    location /5/ {
        proxy_pass http://localhost:7141/;
        proxy_set_header X-Script-Name /5;
    }
}
